### ISSUE TITLE
SIGUNUSED not available in newer glibc

### ISSUE THREAD

**Issue by fifteenhex** [directfb2/DirectFB2#10]
Note: I intend to fix this myself. This is for people googling..

Currently with a newish glibc the build fails because SIGUNUSED has been removed.
I fixed this like this: https://github.com/fifteenhex/DirectFB2/commit/88ec0f41f731463716f791611b97d22c199056a4

**Comment by caramelli** [comment]
Hi Daniel,

SIGUNUSED is now replaced with the standard SIGSYS signal: https://github.com/directfb2/DirectFB2/commit/521eebe4042d988c04930e0e148cf41ac3db085c

Thanks!
