### ISSUE TITLE
Invalid colour mode on qemu/virtio gpu with drmkms backend.

### ISSUE THREAD

**Issue by fifteenhex** [directfb2/DirectFB2#15]
I'll add some more details when I work it out but currently:

- With QEMU's virtio gpu the fbdev backend works fine.
- The drmkms backend has two issues:
-- Some of the display modes that QEMU uses causes the resolution to be weird (the window size which can be any horizontal/vertical size and scaled while running) and that breaks the code that is using the xres and yres table to find a mode. This can be fixed by making sure the resolution is fixed to one of the sizes in the xres/yres table.
-- When setting up the crtc the colour mode passed in is AR24, it seems like one of the planes supports XR24 (main plane I guess? no alpha..) and the other supports AR24 (cursor plane with alpha so that it can overlay on the main one?). The mode getting passed when setting up the crtc is AR24 and the DRM/KMS side in the kernel complains that the color mode is invalid.

**Comment by caramelli** [comment]
The drmkms system module was one of the last developments made in the legacy DirectFB project and has not necessarily been tested very well on many platforms with different configurations.
I have never played with qemu using virtio-gpu but it's something I should try.

**Comment by fifteenhex** [comment]
> The drmkms system module was one of the last developments made in the legacy
> DirectFB project and has not necessarily been tested very well on many platforms with different configurations.

That makes sense. It worked fine with the DRM/KMS driver I wrote for my machine so I don't think it's far off.

> I have never played with qemu using virtio-gpu but it's something I should try.

I think it will make your life easier with testing etc. My target machine only has 128MB of memory so it was very hard to get valgrind and gdb working there to debug the segfaults. A lot easier in QEMU :)

Anyhow,.. I will work this out and send a PR when I have a fix.

**Comment by fifteenhex** [comment]
Found a workaround for now: Setting pixelformat=RGB32 in .directfbrc allows df_fire etc to run.

**Comment by fifteenhex** [comment]
I think now that directfb asks for the mode from the kernel this is also fixed.
