### ISSUE TITLE
Compilation fails because fluxcomp is not working

### ISSUE THREAD

**Issue by ddf5555** [directfb2/DirectFB2#21]
I have compiled fluxcomp from https://github.com/deniskropp/flux
and it's not working after 'ninja - C build', log:

[45/185 ] Generating src / core / flux_source_CoreDFB with a custom command FAILED : src / core / CoreDFB.c src / core / CoreDFB.h usr / local / bin / fluxcomp --call - mode --dispatch - 

![IMG_20220302_170913](https://user-images.githubusercontent.com/100788893/156432179-d29fe46c-51f3-4b3e-9fbb-188467f73a01.jpg)

I use Ubuntu 18.04, where can I get patches you mentioned in other post on github to get fluxcomp working with directfb2?

**Comment by caramelli** [comment]
The latest code available at https://github.com/deniskropp/flux should be used.
For more details, see https://github.com/directfb2/DirectFB2/issues/9

**Comment by ddf5555** [comment]
Tomorrow I will try again, but inside VM with clean installation of ubuntu 20 lts. Can I get fluxcomp 1.4.5? For the first glance it looks obvious that parsed command line argument is invalid, called from build script but I can't find out why. I don't think it's dispatch error because I looked at source code and compared error message with help of usage.

**Comment by caramelli** [comment]
Having a fluxcomp 1.4.5 would probably be the right solution to avoid this kind of issue...

For now:

git clone https://github.com/deniskropp/flux.git
./autogen.sh
./configure
make install

But yes, the idea would be to change FLUXCOMP_MICRO_VERSION from 4 to 5 in the configure.in file, and having a package for distro might be nice.

**Comment by ddf5555** [comment]
I fixed compilation of the fluxcomp with recent version of autoconf. Make fork and I will make pull req. Important patches are in the offing. Directfb2 compilation would work with old distribution, but I will try later.

**Comment by ddf5555** [comment]
I compiled directfb2 on the ubuntu 18.04
If anyone have problem with compilation make sure you have installed following packages: Automake autoconf m4 libtool pkg-config ninja
Install meson from pip, use python-3.7:
pip3 install --user meson

Run meson, or add ~/.local/bin to your $PATH:
~/.local/bin/meson build/

To compile fluxcomp remove autogen.sh, rename configure.in to configure.ac, run:
autoreconf -fi && ./configure && make -j$(nproc) && sudo make install
