### ISSUE TITLE
libkms dependency not met (armbian)

### ISSUE THREAD

**Issue by chrisherman** [directfb2/DirectFB2#34]
Hello, I am trying to install DirectFB2 on an clockwork devterm running armbian:

Linux version 5.10.60-rockchip64 (root@instance-3) (aarch64-linux-gnu-gcc (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36)) 8.3.0, GNU ld (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36)) 2.32.0.20190321) #trunk SMP PREEMPT Thu Jan 13 11:15:04 UTC 2022

No X11/GUI, just command line tools, except for X11 developer sources.
both libdrm and libkms were missing and I managed to get libdrm installed.
Now I am stuck at how to get libkms installed and would be grateful for any advice on how to resolve that dependency.

**Comment by caramelli** [comment]
Once you have built and installed libdrm/libkms using your cross-compiler, create a file named aarch64-linux-gnu containing:

[binaries]
c = 'aarch64-linux-gnu-gcc'
strip = 'aarch64-linux-gnu-strip'
pkgconfig = 'pkg-config'

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7-a'
endian = 'little'

Then run meson for the configuration step:

	meson --cross-file aarch64-linux-gnu build

Note that the libdrm/libkms installation comes with the pkg-config files libdrm.pc and libkms.pc
You may need to set the PKG_CONFIG_LIBDIR and PKG_CONFIG_SYSROOT_DIR environment variables correctly before running meson.

**Comment by caramelli** [comment]
Also note that libdrm/libkms are not necessarily required for the build, it is possible to do some quick tests using the Linux Framebuffer support.

**Comment by Popolon** [comment]
Hi, thanks for your great work, new features seems promising.

I have the same issue on ArchLinux where libdrm is released without libkms. It looks like libkms will not be added soon on Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964453

I made a [directfb2-git](https://aur.archlinux.org/packages/directfb2-git) AUR package, hope it will help a bit, this project to grow.

**Comment by caramelli** [comment]
I didn't know that using libkms was discouraged, thanks.
As the drmkms system module aims to be generic (simple memory-mapped buffers without any driver-dependent code), the libkms dependency can be removed by using dumb buffers: https://github.com/directfb2/DirectFB2/commit/958aab760292281eff4ca41d3de11a8581fa45ef
Note that a system module based on gbm is planned (empty for now): https://github.com/directfb2/DirectFB2-eglgbm 

And thank you very much for packaging on Arch Linux! Just note that there is probably an error in the description of the package and in the license (LGPL).

**Comment by Popolon** [comment]
oops, sorry for the errors on the package, fixed, and thank you very much for the patch.

**Comment by caramelli** [comment]
Code based on gbm is available, all platforms supporting generic buffer management can use the [DirectFB2-eglgbm](https://github.com/directfb2/DirectFB2-eglgbm) system module.
