### ISSUE TITLE
Saw your project, question, about DirectFB2,

### ISSUE THREAD

**Issue by FrostKnight** [directfb2/DirectFB2#42]
what is this project's purpose?

1: Is it to be a minimalistic, replacement for xorg or xenocara that both uses minimal dependencies that work across all unix based systems? 

2: Also, is it meant to increase the security of unix based systems many thousands of times more than something like wayland or xorg or xenocara, with support for BSD as well?

3: And is it planned to support more architectures, long term? 

4: Including anything from x86 to Risc-V and Microwatt and other future designs?

If so, I have a feeling that BSD devs might have huge amounts of interest in this, if they don't already.

They seem to like minimalistic system calls in their design. Particularly, OpenBSD and possibly others.

5: And last but not least, wondering if this supports GUI applications.

As long as they don't require any bloated frameworks, by default.

6: Basically, the default development model, being optional dependencies, for overengineered crap at worst but minimal required dependencies.

At best, not needed at all.

Had interest in looking for an alternative to xorg and xenocara, more or less due to the sheer size of it and the level of usage it requires, also... most alternatives, look spooky to me, with two exceptions, the one that used to be microwindows, although this is still not quite my ideal, the cosmo72 twin repo on github, is the other option, but again, yours looks like it has the most potential in this area.
The smaller and more efficient the code base, the less wasted cpu power, electricity and more secure it will be, which leads to less hardware being killed due to get cracked into.

If you would like, I can tell you why I am interested afterwards, I would like to know if enough of this, has a future.

As an aside, just supporting applications, that require xenocara is sufficient for me, not sure about others.

I appreciate you reviving this project though.

Thoughts?

**Comment by caramelli** [comment]
DirectFB is not a replacement for a windowing system like X11 or Wayland, but it is an option for the graphics stack. And it is possible to get great performance if a graphics accelerator is available on the platform, such as a blitter for block image transfer.

DirectFB was designed for embedded systems and has been widely used in the GNU/Linux embedded world in the past. DirectFB2 was created to maintain DirectFB primarily for use on small systems.
Only the historical Linux support is available at this time, but one of the goals of DirectFB2 is to target embedded operating systems, such as FreeRTOS. I hope to see DirectFB2 running on i.MX RT or STM32 MCUs for example, with a graphics driver module for BLIT operations.

The code is not architecture dependent (generic implementation, possibility to add specific SIMD acceleration), and runs on x86, ARM, MIPS, PowerPC, SuperH platforms for example. I don't see issues for the RISC-V architecture.

I've always had a great interest in the history of UNIX but embedded systems have never led me to BSD systems yet: yes, I'm sure I'd enjoy playing with DirectFB on a BSD system.

For the GUI, feel free to take a look at this wiki: https://directfb2.github.io

**Comment by FrostKnight** [comment]
Hmm... will DirectFB ever be planned to replace X11? 
Also, how much does it cut down the cpu usage and ram usage?
And also, as a last thought, is it more secure and if so by how much?

Btw, regarding historical linux support, I wonder if kisslinux or systems like it, would work well with it.

If I had to guess, probably.

**Comment by caramelli** [comment]
For most of my daily needs on my personal computer, DirectFB is enough for me... If there are any security issues, any suggestions on the current implementation are welcome.

DirectFB2 has no external dependencies except C library such as glibc, uClibc, musl (and also a small tool named fluxcomp to convert some interface descriptions to C files).
So since KISS Linux is based on the Linux kernel, other than a few details, I don't see any real issues running DirectFB2 on this system.
Whenever I start on a new embedded platform, I really enjoy building my system from scratch, just using the Linux kernel, a busybox, and then immediately testing the display with DirectFB2.
Yes, working with a system like KISS Linux, and even on a smaller system with almost nothing, is quite suitable for DirectFB2.

Note that the size of the generated library is around 1MB, but regarding the CPU usage, as explained earlier, it will depend on whether you can use a graphics accelerator for graphics operations.

**Comment by FrostKnight** [comment]
The "no external dependencies except c library" sounds like it probably is way more secure. Btw, not that what I am about to say, is needed, but the only way you could probably make it more secure if true, is to implement something similar to unveil and pledge although, for all I know, such a thing might not be needed regardless of the OS... 

That aside, what dependencies does DirectFB2 require? For that matter, not sure what the first DirectFB required either, well, prior to the redhat movement anywho... 

Btw, when I say dependencies, I mean specifically, what individual packages are needed, as a whole for both DirectFB and DirectFB2

Anywho, regardless, feel free to close this thread after you answer.
Although you could sooner, but yeah, the reason I ask, is because sometimes the requirements in something like archlinux have added dependencies that make no sense.

Aka, redhatware, again...
Oh also forgot, one other thing, does DirectFB2 require root as much as xorg?
So yeah, that will be actually be my last question

My bad, if I ask a lot of questions, let's just say for the sake of time, I didn't even know there was any alternatives to the mess xorg is by default and more so, the mess wayland seems to be already and possibly will be later on even more so.

Though, pure xenocara is probably mild compared to the  above options.  

Actually, if DirectFB2 requires specific dependencies from X11, I wonder which ones are needed and if they could be substituted out for xenocara ones.

Xenocara = more secure xorg

:)

**Comment by FrostKnight** [comment]
Hmm, seems when I typed part of that in, it didn't make the part I wanted bold... it was everything below that spot that I wanted bold.  also, >.> where it was bold to indicate, redhat made me feel nervous for the libre movement and open source movement as well.
Anywho, regardless, feel free to close this thread after you answer.
Although you could sooner, but yeah, the reason I ask, is because sometimes the requirements in something like archlinux have added dependencies that make no sense.
Aka, redhatware, again...
>.>

**Comment by caramelli** [comment]
DirectFB2 has no external dependencies except the C library... Just note that the mentioned fluxcomp tool is only used when building on the host and not embedded into the target (you also need a compiler and meson when building). No graphics library is required on the native host system, a virtual console is more than enough to build and start DirectFB2!

I invite you to look at the DirectFB2 code and play with it. You can be satisfied with the system module based on the legacy framebuffer interface: in this case, you only need the linux/fb.h header file. Or you may prefer the system module based on the modern DRM/KMS interface (yes, I admit you have the libdrm dependency in this case, although it's still possible to remove it by calling ioctl() directly...).
And you also have the possibility to use/develop your own system module: on STM32 microcontrollers for example, it will probably be based on the stm32f4xx_hal_driver component.

**Comment by FrostKnight** [comment]
So more or less, there are close to only 4 direct dependencies? Is that what you mean?

I would need the graphics library for something like JWM though right? its such an awesome window manager, I will tell you that. :)

Btw, isn't HAL deprecated and not really used by anyone? Whether it be minimalists or monolith supporters, meaning people who are fans of fedora and all that other mainstream complex stuff?

In any case, you have got my interest and possibly someone else I know as well.

:)

**Comment by caramelli** [comment]
Be careful not to confuse the host (for building) with the target's rootfs (on which you don't need tools like gcc or meson to just run apps).
But yes, if you build and run DirectFB2 on the same machine (the host), the dependencies remain limited (note that meson depends on Python...).

The stm32f4xx_hal_driver component is really specific to development on STM32 microcontrollers (I want to run DirectFB2 on it) but that doesn't seem to be your area of ​​application.

I'm sorry to say that DirectFB was not designed to run a window manager like JWM: the compositing is performed by a window manager module and you can look to the default window manager module https://github.com/directfb2/DirectFB2/blob/master/wm/default/default.c
This default window manager is minimalist, it is possible to develop your own window manager module (a directfbrc configuration file allows you to specify the window manager module to use).

**Comment by FrostKnight** [comment]
Hmm... curious, but have you heard of codeberg.org/JWMKIT/JWM_KIT
Also, there is something called console-tdm,  I am assuming it doesn't take the place of console-tdm right?
To clarify, I meant that a display manager is still needed.
Since it seems some form of X11 is needed anyways  for DirectFB2 right?
https://github.com/dopsi/console-tdm
Btw, is it easy or hard to make there be an option for using multiple window managers
Actually, as a last question, is there anything that I should be aware of that wouldn't work in a BSD or in general and would it be hard to fix?
Btw, I do mean last this time, otherwise I will drive you nuts asking many, many questions.
This has my interest now though.

I would say more, but I might just ask my dev friend what he knows in the future.

Seems I might be being stupid, I also wondered when a stable release is planned for, etc...

Like which month or year, etc...

;)

Though beta would even be good enough for me to try it out, if it was an option in my distro to use.

Aka, the HyperbolaBSD switch is in alpha last I checked? Could be coming very soon, not sure, but yeah

Have a good one and thanks for doing something both insane and awesome!

I say insane, because going against the grain gets some people riled up, but it is also awesome, because I detest a lot of bloatware and buggy, complexity and lack of privacy/security.

**Comment by caramelli** [comment]
DirectFB does not replace a windowing system like X11 (but the windowing system offered by DirectFB is enough for me). And no form of X11 is needed for DirectFB2.

To have a working DirectFB2, you need:

  - an OS wrapper for things like mutex, threads, ... (cf lib/direct/os/linux on Linux)
  - a system module (fbdev or drmkms on Linux)
  - an input driver module (cf inputdrivers/linux_input on Linux)

If I'm not wrong, libdrm is available on BSD systems. For the input driver module, depending on the input device and available interfaces, a separate module may be used (like https://github.com/directfb2/DirectFB2-tslib for touchscreen devices). I guess most of the lib/direct/os/linux wrapper code could be used on BSD systems.

No tagged releases are planned, all DirectFB2 snapshots are considered stable at this time.

**Comment by FrostKnight** [comment]
I found this:  https://en.wikipedia.org/wiki/DirectFB

Would this still be considered true?

And what is different?

Btw, do you have something similar to DirectFB2 in your repo or know where it is?

I would love to try those two things out to see how well they work together. 

I could use qemu to test it out. If its an option or someone helps me out.

The 2nd thing, is probably something I could ask elsewhere for.

The rootless part + less bloat would be nice.

**Comment by FrostKnight** [comment]
Damn, meant to say similar to XDirectFB... and to ask if your master version is the snapshot...

Either way, the more I find out, the more it has my interest.

**Comment by caramelli** [comment]
DirectFB has now more than 20 years of history, DirectFB2 is a fork of DirectFB in order to preserve and maintain the DirectFB graphics backend.

Functionally, I think XDirectFB can be seen as XWayland. XDirectFB consisted of a patched version of xorg-server (patch which was never merged into the official X.Org repository).
Since DirectFB2 is backwards compatible with DirectFB, there is no problem running XDirectFB using a DirectFB2 snapshot.
I have played with XDirectFB in the past, but that kind of hybrid approach isn't my focus at the moment. Maybe one day someone will also try to revive XDirectFB...

The DirectFB Wikipedia page may not be detailed enough: in particular, OpenGL rendering with DirectFBGL or with EGL can be used without any form of X11 (which was the case on many set-top boxes chipsets such as Intel CE chipsets with PowerVR GPU, ST ARM chipsets with Mali GPU and Broadcom ARM or MIPS chipsets with VideoCore GPU). Additionally, Vulkan rendering using DirectFB can also be done.

If you want more details on the fabulous work done by the DirectFB developers on the core library, feel free to take a look at the various branches before DirectFB2: https://github.com/directfb2/DirectFB2/branches

Note that DirectFB2 has switched to the Meson build system, contains a pure C implementation and source code modularization. In particular, it's more appropriate for porting it to MCU platforms, which is one of my current hobbies.

**Comment by FrostKnight** [comment]
So its possible to use a window manager without XDirectFB? Although, I don't know the level of difficulty, but in any case, it is better if I cut this short...  aka,  I don't want to keep this post opened any longer, in case it distracts from more pressing issues. :)

Thank you for all the information you gave me though. 

But just one very important side note:

DirectFB2 > Xenocara > Xorg > Wayland

DirectFB2 being the best as far as I can see... and well...

you get the picture...

:P

Aka, don't like bloat and this is probably the best so far.  

Anywho, thank you a ton!
