### ISSUE TITLE
How is DirectFB2 different from SDL2

### ISSUE THREAD

**Issue by laoshaw** [directfb2/DirectFB2#72]
Are they complementing each other or they are just different? when/why should I use DirectFB2?

also, can DirectFB2 support lvgl?

**Comment by caramelli** [comment]
DirectFB and SDL projects have a different history. It is true that applications based on SDL could be written using DirectFB.

I would say that SDL is focused on providing a graphics layer for programming cross-platform applications by relying on the graphics stack of the operating system (X11, Wayland, and also DirectFB on a Linux system).

So while DirectFB is not a replacement for a windowing system like X11 or Wayland, it is an option for the graphics stack, historically designed for embedded systems and primarily intended for use on small systems. And if a graphics accelerator is available on the platform, DirectFB aims to use hardware acceleration to perform graphics operations with a specific graphics driver module.

LVGL has a SDL2 port available, so LVGL applications can run on a DirectFB platform via SDL2 (it would be possible to write a LVGL port directly on top of DirectFB2).

LVGL is focused on providing user interface components designed for MCUs. One of the goals of DirectFB2 is also to target MCUs operating systems, such as NuttX or FreeRTOS: I hope to see DirectFB2 running on iMX RT or STM32 MCUs for example, with a graphics driver module for BLIT operations. And the LiTE library aims to provide user interface widgets on top of DirectFB. There is still a lot to do and any help is welcome!

Playing with DirectFB2 is a matter of choice: the DirectFB2 project doesn't have the importance of SDL2 or LVGL, but I consider it important to preserve this historical graphics backend for its technical side and its free software philosophy.

**Comment by laoshaw** [comment]
DirectFB2 definitely has its place, esp in embedded fields. I plan to use it in my own embedded projects.
