### ISSUE TITLE
DFBTerm Installation

### ISSUE THREAD

**Issue by Greijus** [directfb2/DirectFB2#77]
DFBTerm depends on the LiTE library. So you need to install LiTE first (same way as DirectFB2) and then install DFBTerm
Switch to a virtual console and run dfbterm using sudo

_Originally posted by @caramelli in https://github.com/directfb2/DirectFB2/issues/74#issuecomment-1367431484_

**Comment by Greijus** [comment]
Please could you give directions on how to install the DBFTerm? I already installed LiTE and LiTE-examples... Thanks.

**Comment by caramelli** [comment]
To install DBFTerm, it's the same as DirectFB2 or LiTE (as documented in https://github.com/directfb2/DFBTerm/blob/master/INSTALL).
Then you can run dfbterm (the same way you run the df_andi example).

**Comment by Greijus** [comment]
Thank you. I didn't know that there is a separate repository for the DFBTerm. Is already installed and working :)
