### ISSUE TITLE
directfb-config: not found

### ISSUE THREAD

**Issue by Greijus** [directfb2/DirectFB2#89]
Hi,

I succesfully installed DirectFB2 and FusionSound2 manbually in my target system (x86-64) and executed the examples. My taget is running a Linux distro generated with Yocto. 

I've been trying to re-compile an app in my target system. Originally the app was compiled using Directfb-1.4.9 and fusionsound-1.1.. many years ago. However, when I execute the `make` cmd, I get this output in my terminal:

```
g++ -c -DDEBUG=1 -Wall -O2 `directfb-config --cflags` -pipe  -o debug/main.o main.cpp
/bin/sh: 1: directfb-config: not found
```
I have an extra target system with DirectFB-1.8.0 installed, and when compiling the app, I don't see this issue.

Do you have any ideas on how can I solve this? 

This is how the flags are configured in the Makefile:

```
CC = gcc
CXX = g++
CFLAGS = -Wall -O2 `directfb-config --cflags` -pipe
LFLAGS = -lpng -lrt `directfb-config --libs` -lfusionsound
CXXFLAGS = $(CFLAGS)
```
Thanks!

**Comment by caramelli** [comment]
pkg-config is the program to use with DirectFB2 or FusionSound2:

	pkg-config --cflags directfb
	pkg-config --libs directfb
	pkg-config --cflags fusionsound
	pkg-config --libs fusionsound

**Comment by Greijus** [comment]
Thanks! This solved my issue in compiling in new target
